[package]
name = "image-processing-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "image_processing_ffi"
crate-type = ["cdylib"]

[dependencies]
image = "0.24"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 